### GET ALL ITEMS
GET http://localhost:5050/api/items

### GET ONE ITEM
GET http://localhost:5050/api/items/646d3f9dcdba835951b289df

### CREATE NEW ITEM
POST http://localhost:5050/api/items
Content-Type: application/json

{
  "item": "tech-talk mern"
}

### UPDATE ITEM
PATCH http://localhost:5050/api/items/646df818be7965a6387f1314
Content-Type: application/json

{
  "item": "react.js"
}

### DELETE ITEM
DELETE http://localhost:5050/api/items/646df818be7965a6387f1314